version: '3.8'

services:
  geoserver:
    image: kartoza/geoserver:latest
    container_name: geoserver
    ports:
      - "8080:8080"
    volumes:
      - ./data:/opt/geoserver/data_dir
    environment:
      - GEOSERVER_ADMIN_PASSWORD=geoserver
    networks:
      - geoserver-network

networks:
  geoserver-network:
    driver: bridge